### ISSUE TITLE
Question: Is there a checklist how to adjust this repository to a different GTFS Schedule feed & Hafas client?

### ISSUE THREAD

**Issue by dancesWithCycles** [derhuerst/berlin-gtfs-rt-server#12]
Hi!
Thank you so much for providing and maintaining this repository.

I forked this repository to evaluate if it is possible to replicate it for a different GTFS Schedule feed and Hafas client.

I am wondering how a checklist could look like that provide an overview for the task ahead. I found the following places that are specific to https://github.com/derhuerst/berlin-gtfs-rt-server and need an adjustment.

- Provide GTFS Schedule feed to database: https://github.com/derhuerst/berlin-gtfs-rt-server/blob/7e9e095878ae3ea13c976fee1fa3e39643ed28b2/build.sh#L7)
- Provide URL to GTFS Schedule feed: https://github.com/derhuerst/berlin-gtfs-rt-server/blob/7e9e095878ae3ea13c976fee1fa3e39643ed28b2/start.sh#L29)
- https://github.com/derhuerst/berlin-gtfs-rt-server/blob/7e9e095878ae3ea13c976fee1fa3e39643ed28b2/package.json#L48
- How/Where do I provide the specific Hafas client?

Whats missing?

Cheers!

**Comment by derhuerst** [comment]
> I forked this repository to evaluate if it is possible to replicate it for a different GTFS Schedule feed and Hafas client.

This is what [`hafas-gtfs-rt-feed`](https://github.com/derhuerst/hafas-gtfs-rt-feed) (a dependency of `berlin-gtfs-rt-server`) is for; Simplified: Pass in a HAFAS client & a GTFS Static/Schedule feed, and obtain a GTFS Realtime feed.

You can either build your own GTFS Realtime feed "bottom up", by following `hafas-gtfs-rt-feed`'s docs, or "top-down" by copying/forking this repository and adapting all Berlin-/VBB-specific parts.

Does that answer your question?

**Comment by derhuerst** [comment]
> * How/Where do I provide the specific Hafas client?

This happens here:

https://github.com/derhuerst/berlin-gtfs-rt-server/blob/d0542b72111c081334bbe611718e2015435ba59b/start.sh#L16

And this is the HAFAS client:

https://github.com/derhuerst/berlin-gtfs-rt-server/blob/d0542b72111c081334bbe611718e2015435ba59b/lib/hafas.js

**Comment by dancesWithCycles** [comment]
Cheers mate! I'll give it a try. ;-)

**Comment by derhuerst** [comment]
I'll close this Issue then. Please file subsequent bugs and questions about `hafas-gtfs-rt-feed` in its repo.
